<?php

namespace AppBundle\Repository;

/**
 * VIPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VIPRepository extends \Doctrine\ORM\EntityRepository
{
}
